export const styles = {
    container: {
        maxWidth: "640px",
        margin: "40px auto",
        padding: "32px",
        backgroundColor: "#ffffff",
        borderRadius: "14px",
        fontFamily: "var(--font-nunito), 'Nunito', sans-serif",
        color: "#292929",
    },
    form: {
        display: "flex",
        flexDirection: "column",
        gap: "20px",
    },
    input: {
        padding: "12px",
        border: "1px solid #6b7280",
        borderRadius: "0",
        fontSize: "16px",
        fontFamily: "var(--font-nunito), 'Nunito', sans-serif",
        color: "#292929",
        backgroundColor: "#ffffff",
        outline: "none",
    },
    button: {
        padding: "12px 48px",
        backgroundColor: "#267151",
        color: "#ffffff",
        border: "none",
        borderRadius: "0",
        cursor: "pointer",
        fontSize: "16px",
        fontWeight: 800,
        fontFamily: "var(--font-nunito), 'Nunito', sans-serif",
        textDecoration: "none",
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        transition: "background-color 0.15s ease",
    },
    buttonDisabled: {
        padding: "12px 48px",
        backgroundColor: "rgba(38, 113, 81, 0.5)",
        color: "#ffffff",
        border: "none",
        borderRadius: "0",
        cursor: "not-allowed",
        fontSize: "16px",
        fontWeight: 800,
        fontFamily: "var(--font-nunito), 'Nunito', sans-serif",
    },
    error: {
        padding: "12px",
        color: "#b91c1c",
        backgroundColor: "#fecaca",
        marginTop: "10px",
        fontSize: "14px",
        fontWeight: 600,
        borderRadius: "4px",
    },
    h2: {
        margin: "0 0 24px 0",
        fontSize: "1.875rem",
        lineHeight: "2.25rem",
        fontWeight: 700,
        color: "#292929",
        textAlign: "center" as const,
    },
    signed_in_msg: {
        padding: "20px",
        backgroundColor: "#dcfce7",
        color: "#15803d",
        borderRadius: "4px",
        marginTop: "20px",
        fontWeight: 600,
    },
    separator: {
        display: "flex",
        alignItems: "center",
        textAlign: "center" as const,
        margin: "20px 0",
    },
    separatorLine: {
        flex: 1,
        borderBottom: "1px solid #d1d5db",
    },
    separatorText: {
        padding: "0 12px",
        color: "#525252",
        fontSize: "13px",
        fontWeight: 700,
        textTransform: "uppercase" as const,
        letterSpacing: "0.05em",
    },
    socialButton: {
        padding: "12px",
        backgroundColor: "#ffffff",
        color: "#292929",
        border: "1px solid #6b7280",
        borderRadius: "0",
        cursor: "pointer",
        fontSize: "16px",
        fontWeight: 700,
        fontFamily: "var(--font-nunito), 'Nunito', sans-serif",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        gap: "10px",
        transition: "background-color 0.2s, border-color 0.2s",
    },
    providerLogo: {
        fontSize: "20px",
        display: "flex",
        alignItems: "center",
    },
} as const;
