export const styles = {
    pageWrapper: {
        backgroundColor: "#f5f5f5",
        minHeight: "100vh",
        fontFamily: "var(--font-nunito), 'Nunito', sans-serif",
        color: "#292929",
    },
    hero: {
        backgroundColor: "#098851",
        padding: "3.75rem 0",
    },
    heroInner: {
        width: "85%",
        maxWidth: "80rem",
        margin: "0 auto",
    },
    heroTitle: {
        margin: 0,
        color: "#ffffff",
        fontSize: "2rem",
        lineHeight: "2.5rem",
        fontWeight: 700,
    },
    card: {
        width: "85%",
        maxWidth: "80rem",
        margin: "-2.5rem auto 2.5rem",
        padding: "3.5rem 3rem",
        backgroundColor: "#ffffff",
        position: "relative" as const,
    },
    cardInner: {
        maxWidth: "40rem",
        margin: "0 auto",
    },
    container: {
        maxWidth: "40rem",
        margin: "2.5rem auto",
        padding: "2rem",
        backgroundColor: "#ffffff",
        borderRadius: "0.875rem",
        fontFamily: "var(--font-nunito), 'Nunito', sans-serif",
        color: "#292929",
    },
    stepHeading: {
        margin: "0 0 1rem 0",
        fontSize: "1.75rem",
        lineHeight: "2.25rem",
        fontWeight: 700,
        color: "#000",
    },
    form: {
        display: "flex",
        flexDirection: "column",
        gap: "1.75rem",
    },
    formFieldLabel: {
        fontSize: "0.875rem",
        fontWeight: 600,
        color: "#292929",
        marginBottom: "-0.75rem",
    },
    guideBox: {
        border: "1px solid #267151",
        padding: "1.5rem 1.25rem",
        backgroundColor: "#ffffff",
    },
    guideTitle: {
        fontSize: "1.125rem",
        fontWeight: 700,
        color: "#292929",
        marginBottom: "0.75rem",
    },
    guideList: {
        margin: 0,
        paddingLeft: "2rem",
        fontSize: "1rem",
        lineHeight: "1.6",
        color: "#292929",
    },
    sentBanner: {
        backgroundColor: "#dcfce7",
        border: "1px solid #267151",
        color: "#15803d",
        padding: "1.25rem 1rem",
        fontSize: "1rem",
        fontWeight: 600,
    },
    actionsRow: {
        display: "flex",
        alignItems: "center",
        gap: "2.5rem",
        marginTop: "0.5rem",
    },
    cancelLink: {
        background: "none",
        border: "none",
        padding: 0,
        cursor: "pointer",
        color: "#267151",
        fontSize: "1.125rem",
        fontWeight: 800,
        fontFamily: "var(--font-nunito), 'Nunito', sans-serif",
    },
    resendLine: {
        marginTop: "0.75rem",
        fontSize: "1rem",
        fontWeight: 700,
        color: "#267151",
    },
    resendButton: {
        background: "none",
        border: "none",
        padding: 0,
        cursor: "pointer",
        color: "#267151",
        fontSize: "1rem",
        fontWeight: 800,
        textDecoration: "underline",
        fontFamily: "var(--font-nunito), 'Nunito', sans-serif",
    },
    input: {
        padding: "1rem",
        border: "1px solid #6b7280",
        borderRadius: "0",
        fontSize: "1.125rem",
        fontFamily: "var(--font-nunito), 'Nunito', sans-serif",
        color: "#292929",
        backgroundColor: "#ffffff",
        outline: "none",
    },
    button: {
        padding: "0.875rem 3rem",
        backgroundColor: "#267151",
        color: "#ffffff",
        border: "none",
        borderRadius: "0",
        cursor: "pointer",
        fontSize: "1.125rem",
        fontWeight: 800,
        fontFamily: "var(--font-nunito), 'Nunito', sans-serif",
        textDecoration: "none",
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        transition: "background-color 0.15s ease",
    },
    buttonDisabled: {
        padding: "0.875rem 3rem",
        backgroundColor: "rgba(38, 113, 81, 0.5)",
        color: "#ffffff",
        border: "none",
        borderRadius: "0",
        cursor: "not-allowed",
        fontSize: "1.125rem",
        fontWeight: 800,
        fontFamily: "var(--font-nunito), 'Nunito', sans-serif",
    },
    error: {
        padding: "0.75rem",
        color: "#b91c1c",
        backgroundColor: "#fecaca",
        marginBottom: "0.75rem",
        fontSize: "0.875rem",
        fontWeight: 600,
    },
    h2: {
        margin: "0 0 1.5rem 0",
        fontSize: "1.875rem",
        lineHeight: "2.25rem",
        fontWeight: 700,
        color: "#292929",
        textAlign: "center" as const,
    },
    signed_in_msg: {
        padding: "1.25rem",
        backgroundColor: "#dcfce7",
        color: "#15803d",
        borderRadius: "0.25rem",
        marginTop: "1.25rem",
        fontWeight: 600,
    },
    separator: {
        display: "flex",
        alignItems: "center",
        textAlign: "center" as const,
        margin: "1.25rem 0",
    },
    separatorLine: {
        flex: 1,
        borderBottom: "1px solid #d1d5db",
    },
    separatorText: {
        padding: "0 0.75rem",
        color: "#525252",
        fontSize: "0.8125rem",
        fontWeight: 700,
        textTransform: "uppercase" as const,
        letterSpacing: "0.05em",
    },
    socialButton: {
        padding: "0.75rem",
        backgroundColor: "#ffffff",
        color: "#292929",
        border: "1px solid #6b7280",
        borderRadius: "0",
        cursor: "pointer",
        fontSize: "1rem",
        fontWeight: 700,
        fontFamily: "var(--font-nunito), 'Nunito', sans-serif",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        gap: "0.625rem",
        transition: "background-color 0.2s, border-color 0.2s",
    },
    providerLogo: {
        fontSize: "1.25rem",
        display: "flex",
        alignItems: "center",
    },
    label: {
        fontSize: "1.0625rem",
        fontWeight: 500,
        color: "#292929",
        textAlign: "left" as const,
        marginBottom: "-1.25rem",
    },
    fieldLabel: {
        fontSize: "0.8125rem",
        fontWeight: 500,
        color: "#525252",
        marginBottom: "-0.75rem",
    },
    checkboxLabel: {
        display: "flex",
        alignItems: "center",
        gap: "0.5rem",
        fontSize: "1rem",
        color: "#292929",
        cursor: "pointer",
        fontWeight: 500,
    },
    inputWrapper: {
        position: "relative" as const,
        display: "block",
    },
    inputWithToggle: {
        padding: "1rem",
        paddingRight: "5rem",
        border: "1px solid #6b7280",
        borderRadius: "0",
        fontSize: "1.125rem",
        fontFamily: "var(--font-nunito), 'Nunito', sans-serif",
        color: "#292929",
        backgroundColor: "#ffffff",
        outline: "none",
        width: "100%",
        boxSizing: "border-box" as const,
    },
    showToggle: {
        position: "absolute" as const,
        right: "1rem",
        top: "50%",
        transform: "translateY(-50%)",
        background: "none",
        border: "none",
        padding: 0,
        cursor: "pointer",
        color: "#267151",
        fontSize: "1rem",
        fontWeight: 700,
        fontFamily: "var(--font-nunito), 'Nunito', sans-serif",
        textDecoration: "underline",
    },
    termsQuestion: {
        fontSize: "1.0625rem",
        fontWeight: 500,
        color: "#292929",
        marginBottom: "0.5rem",
    },
    termsLink: {
        color: "#267151",
        fontWeight: 800,
        textDecoration: "underline",
    },
} as const;
